### ISSUE TITLE
File upload stops working once app is killed on iOS - example app

### ISSUE THREAD

**Issue by bachras** [fluttercommunity/flutter_uploader#173]
Hi,

I have tried example app and it seems to work. I have changed url to send to my server and it work fine, but when I start sending files on iOS and straight kill the app, only few files are sent and the rest never come. Android acts a bit different it stops sending as well once app is killed and sends partial request, but after few moments it sends full request with all the files. Am I missing anything? How I can send files in the background on iOs? Thnaks

**Comment by ened** [comment]
@bachras this may be due to how the background processing is currently handled. iOS side is using the "Fetch" background mode, which runs at most once a day and when the phone is idle. Try to connect your phone to a power source. Additionally, background fetch requests may get cancelled on iOS when the App is killed (using swipe -away from task manager). I'll research a bit on that.

**Comment by ened** [comment]
@bachras please see the discussion in https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1407496-background
If you kill the App using the task manager, then iOS will cancel the upload tasks.
